all:
        pdflatex  main
        bibtex main
        pdflatex  main
        pdflatex  main

clean:
	rm -f *.toc *.aux *.out *.blg *.bbl *.log *.snm *.nav *.pre *.dvi *.auxlock *.ps *.dpth *.dep *Notes.bib
        rm *-eps-converted-to.pdf

